spring.application.name=toeic-service
spring.datasource.url=jdbc:postgresql://localhost:5432/toeic_db
spring.datasource.username=postgres
spring.datasource.password=Dinhluu1259@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.signerKey=z8N4p2qR5vT8xW1zY3mQ6bV9dS2fG5hJ8kL1nP4rS7uX0wZ3aC6vB9nM2r5vT8xW1zY3mQ6bV9d